[package]
name = "indicate-svs-bridge"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[lints]
workspace = true

[dependencies]
indicate-instrument-hmd = { path = "../hmd-set" }
indicate-instrument-state.workspace = true
indicate-instrument-scene.workspace = true
indicate-instrument-descriptor.workspace = true
indicate-instrument-glyphs.workspace = true
libm.workspace = true
