//! The operator names of the style specification.

use serde_json::Value as Json;

/// Every operator name of the style specification, implemented here or not, so a literal
/// array value is told apart from an expression the way GL JS `isExpression` does.
const OPERATORS: &[&str] = &[
    "array",
    "boolean",
    "collator",
    "format",
    "image",
    "literal",
    "number",
    "number-format",
    "object",
    "string",
    "to-boolean",
    "to-color",
    "to-number",
    "to-string",
    "typeof",
    "accumulated",
    "feature-state",
    "geometry-type",
    "id",
    "line-progress",
    "properties",
    "at",
    "get",
    "global-state",
    "has",
    "in",
    "index-of",
    "length",
    "slice",
    "!",
    "!=",
    "<",
    "<=",
    "==",
    ">",
    ">=",
    "all",
    "any",
    "case",
    "coalesce",
    "match",
    "within",
    "interpolate",
    "interpolate-hcl",
    "interpolate-lab",
    "step",
    "let",
    "var",
    "concat",
    "downcase",
    "is-supported-script",
    "resolved-locale",
    "upcase",
    "rgb",
    "rgba",
    "to-rgba",
    "-",
    "*",
    "/",
    "%",
    "^",
    "+",
    "abs",
    "acos",
    "asin",
    "atan",
    "ceil",
    "cos",
    "distance",
    "e",
    "floor",
    "ln",
    "ln2",
    "log10",
    "log2",
    "max",
    "min",
    "pi",
    "round",
    "sin",
    "sqrt",
    "tan",
    "zoom",
    "elevation",
    "heatmap-density",
    "split",
    "join",
];

/// Whether a JSON array is an expression rather than a literal array value: it starts with an
/// operator name, as GL JS `isExpression` decides.
pub fn is_expression(items: &[Json]) -> bool {
    items
        .first()
        .and_then(Json::as_str)
        .is_some_and(|name| OPERATORS.contains(&name))
}
