include "basic.fbs";

struct FlatSymbolVertex {
    a_pos_offset: [int:4];
    a_data: [uint:4];
    a_pixeloffset: [int:4];
}

table FlatSymbolLayerTessellated {
    coords: FlatWorldTileCoords;
    layer_name: string;
    unused_vertices: [ubyte] (deprecated);
    unused_indices: [uint] (deprecated);
    unused_usable_indices: uint (deprecated);
    unused_feature_indices: [uint] (deprecated);
    vertices: [FlatSymbolVertex];
    indices: [uint];
    usable_indices: uint;
    style_layer_id: string;
    symbol_features: [ubyte];
    symbol_atlas: [ubyte];
}

root_type FlatSymbolLayerTessellated;
