name: Build documentation

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean


jobs:
  build-docs:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install mdbook
        uses: ./.github/actions/cargo-install
        with:
          name: mdbook
      - name: Install Dependencies
        uses: ./.github/actions/install-system-dependencies
      - name: Build
        working-directory: docs
        shell: bash
        run: |
          ./generate-summary.sh
          mdbook build
      - name: API Documentation
        shell: bash
        run: cargo doc -p maplibre --no-deps --lib --document-private-items
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: api-docs
          path: target/doc/
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: book
          path: docs/book/
  deploy-docs:
    needs: build-docs
    if: inputs.deploy
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.0
      - name: Download api-docs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: api-docs
          path: artifacts/api
      - name: Download book
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: book
          path: artifacts/book
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages
          folder: artifacts
          target-folder: docs
